version: "3"

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/volumes/nginx/nginx_secrets:/etc/letsencrypt
      - ${PWD}/volumes/nginx/user_conf.d:/etc/nginx/user_conf.d:ro
    environment:
      CERTBOT_EMAIL: alexwbtg@gmail.com

networks:
  default:
    external:
      name: net1
